CC = gcc
CFLAGS = -Wall -Wextra -std=c99
SDL_INCLUDE = -IC:/SDL2/x86_64-w64-mingw32/include/SDL2
SDL_LIB = -LC:/SDL2/x86_64-w64-mingw32/lib -lSDL2main -lSDL2

SRC = main.c game.c graphics.c snake.c map.c
OBJ = $(SRC:.c=.o)
EXEC = snake

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(SDL_LIB)

%.o: %.c
	$(CC) $(CFLAGS) $(SDL_INCLUDE) -c $< -o $@

clean:
	del /f /q $(OBJ) $(EXEC).exe

run: $(EXEC)
	.\$(EXEC)